[workspace]
authors = ["dacher <mael.dacher@student.isae-supaero.fr>"]
channels = ["conda-forge"]
name = "BE-Ising_2025"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
notebook = ">=7.4.7,<8"
numpy = ">=2.3.4,<3"
matplotlib = ">=3.10.7,<4"
